name: Build CybersecurityChatbot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # C# requires Windows for System.Media.SoundPlayer

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Adjust to your .NET version (e.g., 6.0.x or 8.0.x)

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test build output
      run: dir ./bin/Release/net8.0/  # Verify build artifacts (adjust path if needed)
